apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: modelflow
          image: 003014710138.dkr.ecr.eu-west-1.amazonaws.com/modelflow:modelflow-newtag-this-will-get-replaced
          ports:
            - containerPort: 8000