apiVersion: apps/v1
kind: Deployment
metadata:
  name: modelflow
  labels:
    app: modelflow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: modelflow
  template:
    metadata:
      labels:
        app: modelflow
    spec:
      containers:
        - name: modelflow
          image: modelflow
          ports:
            - containerPort: 8000