apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- postgres-configmap.yaml
- ps-deployment.yaml
- ps-service.yaml
- psql-claim.yaml
- psql-pv.yaml
images:
- name: modelflow
  newName: modelflow
  newTag: v0
