
name: create eksctl

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: "eu-west-1"

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: install eksctl and create cluster
        id: create-cluster
        run: |
          if [[ $(aws eks list-clusters --profile github-actions-aws --region eu-west-1 | grep modelFlow) ]]; then
            aws ecr create-repository --repository-name modelflow --region eu-west-1
            ARCH=amd64
            PLATFORM=$(uname -s)_$ARCH            
            curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
            curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check
            tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
            sudo mv /tmp/eksctl /usr/local/bin
            eksctl create cluster -f ${{ github.workspace }}/eksctl-setup/cluster.yaml
          
          fi
          aws eks update-kubeconfig --name modelFlow
      - name: build Docker
        id: build-docker
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 003014710138.dkr.ecr.eu-west-1.amazonaws.com
          docker build . -t modelflow
          docker tag modelflow:latest 003014710138.dkr.ecr.eu-west-1.amazonaws.com/modelflow:latest
          docker push 003014710138.dkr.ecr.eu-west-1.amazonaws.com/modelflow:latest
      - name: deploy
        id: deploy
        run: |
          kubectl apply -f deployment.yaml