name: Delete GKE cluster

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: autopilot-cluster-1    # cluster name
  GKE_ZONE: europe-west1   # cluster zone
  GAR_ZONE: europe-west1 # artifact registry zone

jobs:
  login-delete:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
      - name: delete-gke
        run: gcloud container clusters delete CLUSTER_NAME --region $GKE_ZONE --quiet